import { readFile } from "node:fs/promises";
export function checkStaging(config, requireProvisioned = false) {
  const stage = config.env?.staging;
  const budget = Number(stage?.vars?.OPERATION_DAILY_LIMIT);
  if (!stage || stage.name !== "fresh402-staging" || stage.vars?.ENVIRONMENT !== "staging" || !['gateway','container'].includes(stage.vars.TARGET_FETCH_MODE) || stage.vars.TARGET_HOST_ALLOWLIST !== undefined || !Number.isSafeInteger(budget) || budget > 1000 || budget < 0) throw new Error("Unsafe staging identity, secure egress mode or budget");
  if (stage.d1_databases?.length !== 1 || stage.d1_databases[0].binding !== "DB" || stage.d1_databases[0].database_name !== "fresh402-staging-db" || config.d1_databases.some(db=>db.database_id === stage.d1_databases[0].database_id)) throw new Error("Staging must use its own D1 database");
  if (requireProvisioned && stage.d1_databases[0].database_id === "00000000-0000-0000-0000-000000000000") throw new Error("Staging database has not been provisioned with owner approval");
  const names = ["REQUEST_LIMITER","REGISTER_TARGET_LIMITER","REGISTER_GLOBAL_LIMITER"];
  if (names.some(name=>!stage.ratelimits?.some(limit=>limit.name===name)) || stage.ratelimits.some(limit=>config.ratelimits.some(prod=>prod.namespace_id===limit.namespace_id))) throw new Error("Staging rate limit bindings must be separate");
  if (stage.preview_urls !== false || !Number.isSafeInteger(stage.limits?.cpu_ms) || stage.limits.cpu_ms < 1 || stage.limits.cpu_ms > 1000 || !Number.isSafeInteger(stage.limits?.subrequests) || stage.limits.subrequests < 1 || stage.limits.subrequests > 50 || stage.services || stage.vpc_services || stage.vpc_networks || !stage.triggers?.crons.length) throw new Error("Unsafe staging egress, preview or execution settings");
  if(stage.vars.TARGET_FETCH_MODE==='container') {
    if(stage.version_metadata?.binding!=='CF_VERSION_METADATA'||stage.durable_objects?.code_update_strategy?.mode!=='immediate')throw new Error('Staging requires authoritative release metadata and immediate Durable Object activation');
    const number=name=>Number(stage.vars[name]),pool=number('GATEWAY_POOL_SIZE'),parallel=number('GATEWAY_INSTANCE_CONCURRENCY');
    if(!Number.isInteger(pool)||pool<1||pool>2||!Number.isInteger(parallel)||parallel<1||parallel>4||!['0','1'].includes(stage.vars.CONTAINER_EGRESS_ENABLED)||!Number.isInteger(number('GATEWAY_RUNTIME_BUDGET_SECONDS'))||number('GATEWAY_RUNTIME_BUDGET_SECONDS')>300||number('GATEWAY_RUNTIME_BUDGET_SECONDS')<60||!Number.isInteger(number('OPERATION_CONCURRENCY'))||number('OPERATION_CONCURRENCY')<1||number('OPERATION_CONCURRENCY')>pool*parallel||!Number.isInteger(number('FREE_REGISTRATION_DAILY_LIMIT'))||number('FREE_REGISTRATION_DAILY_LIMIT')<0||number('FREE_REGISTRATION_DAILY_LIMIT')>50||!/^[a-f\d]{64}$/.test(stage.vars.GATEWAY_CODE_HASH??''))throw new Error('Unsafe staging Container capacity or budget');
    if(stage.containers?.length!==1||stage.containers[0].class_name!=='Fresh402Egress'||stage.containers[0].max_instances!==pool||stage.containers[0].instance_type!=='lite'||stage.containers[0].image!=='./gateway/Dockerfile'||stage.containers[0].image_build_context!=='.'||stage.durable_objects?.bindings?.length!==1||stage.durable_objects.bindings[0].name!=='EGRESS_CONTAINER'||stage.durable_objects.bindings[0].class_name!=='Fresh402Egress'||stage.durable_objects.bindings[0].script_name||stage.migrations?.length!==1||stage.migrations[0].tag!=='staging-egress-v1'||stage.migrations[0].new_sqlite_classes?.join(',')!=='Fresh402Egress')throw new Error('Unsafe staging Container artifact or binding');
    if(!/^[a-zA-Z0-9_-]{1,80}$/.test(stage.vars.GATEWAY_BUDGET_WINDOW??'')||!Number.isSafeInteger(number('GATEWAY_BUDGET_EXPIRES_MS'))||number('GATEWAY_BUDGET_EXPIRES_MS')<0||stage.vars.CONTAINER_EGRESS_ENABLED==='1'&&(number('GATEWAY_BUDGET_EXPIRES_MS')<=Date.now()+20_000||number('GATEWAY_BUDGET_EXPIRES_MS')>Date.now()+30*60_000))throw new Error('Staging Container pilot must have an explicit short-lived budget window');
    if(!Number.isInteger(number('VERIFIED_PAYMENT_DAILY_LIMIT'))||number('VERIFIED_PAYMENT_DAILY_LIMIT')<0||number('VERIFIED_PAYMENT_DAILY_LIMIT')>2000||!Number.isInteger(number('OPERATION_ISOLATE_CONCURRENCY'))||number('OPERATION_ISOLATE_CONCURRENCY')<1||number('OPERATION_ISOLATE_CONCURRENCY')>4)throw new Error('Unsafe staging verification or isolate budget');
  } else if(stage.containers||stage.durable_objects||stage.migrations)throw new Error('Unexpected Container resources in external gateway mode');
}
if (process.argv[1]?.replaceAll("\\","/").endsWith("/staging-check.mjs")) {
  const raw = await readFile(new URL("../wrangler.jsonc",import.meta.url),"utf8");
  checkStaging(JSON.parse(raw.slice(raw.indexOf("{"))),process.argv.includes("--provisioned"));
  process.stdout.write("Staging configuration is isolated. No cloud resources were changed.\n");
}
